In [0]:
%tensorflow_version 2.x


In [4]:
!wget https://www.dropbox.com/s/coohig3aj2i283b/mcml_final.csv?dl=0

--2020-05-26 22:21:13--  https://www.dropbox.com/s/coohig3aj2i283b/mcml_final.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.1, 2620:100:601b:1::a27d:801
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/coohig3aj2i283b/mcml_final.csv [following]
--2020-05-26 22:21:13--  https://www.dropbox.com/s/raw/coohig3aj2i283b/mcml_final.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uccc320820bc4b96f0a34ed8dd26.dl.dropboxusercontent.com/cd/0/inline/A4cMGjkU32c4efz0VjQHZLyfeTOVsEf_HZb6K8OB4gl3v-PQsNqbyTloQ4farUD4WT83nSQaus8_x1MIYqmfhOVETi1ld_tSJQSwUS9eIUYnS_BNE6-ex99JEQFJMyQDNro/file# [following]
--2020-05-26 22:21:13--  https://uccc320820bc4b96f0a34ed8dd26.dl.dropboxusercontent.com/cd/0/inline/A4cMGjkU32c4efz0VjQHZLyfeTOVsEf_HZb6K8OB4gl3v-PQsNqbyTloQ4farUD4WT83nSQaus8_x1MIYqmfhOVETi1ld_tSJQSwUS9

In [0]:
# Word2Vec Embeddings used here:

In [5]:
!wget http://vectors.nlpl.eu/repository/20/0.zip

--2020-05-26 22:22:38--  http://vectors.nlpl.eu/repository/20/0.zip
Resolving vectors.nlpl.eu (vectors.nlpl.eu)... 129.240.189.225
Connecting to vectors.nlpl.eu (vectors.nlpl.eu)|129.240.189.225|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 344050746 (328M) [application/zip]
Saving to: ‘0.zip’

0.zip               100%[===================>] 328.11M  21.2MB/s    in 21s     

2020-05-26 22:23:00 (15.9 MB/s) - ‘0.zip’ saved [344050746/344050746]



In [6]:
# name of the file will change if you download a different embedding file
!unzip 0.zip

Archive:  0.zip
  inflating: meta.json               
  inflating: model.bin               
  inflating: model.txt               
  inflating: README                  


In [7]:
!head -10 model.txt
# if the download does not come with a .txt file [only .bin file is there], you'll have to 
# use package gensim to load and convert 

163473 300
say_VERB -0.008861 0.097097 0.100236 0.070044 -0.079279 0.000923 -0.012829 0.064301 -0.029405 -0.009858 -0.017753 0.063115 0.033623 0.019805 0.052704 -0.100458 0.089387 -0.040792 -0.088936 0.110212 -0.044749 0.077675 -0.017062 -0.063745 -0.009502 -0.079371 0.066952 -0.070209 0.063761 -0.038194 -0.046252 0.049983 -0.094985 -0.086341 0.024665 -0.112857 -0.038358 -0.007008 -0.010063 -0.000183 0.068841 0.024942 -0.042561 -0.044576 0.010776 0.006323 0.088285 -0.062522 0.028216 0.088291 0.033231 -0.033732 -0.002995 0.118994 0.000453 0.158588 -0.044475 -0.137629 0.066080 0.062824 -0.128369 -0.087959 0.028080 0.070063 0.046700 -0.083278 -0.118428 0.071118 0.100757 0.017944 0.026296 0.017282 -0.082127 -0.006148 0.002967 -0.032857 -0.076493 -0.072842 -0.055179 -0.081703 0.011437 -0.038698 -0.062540 -0.027899 0.087635 0.031870 0.029164 0.000524 -0.039895 -0.055559 0.024582 -0.030595 0.003942 -0.034500 0.003012 -0.023863 0.033831 0.061476 -0.090183 -0.039206 -0.026586 -0.042763 0.049835

In [0]:
embeding_index={}

f=open('/content/model.txt',encoding='utf-8')

for i,line in enumerate(f):
    if i==0:continue
    values=line.split()
    word=values[0].split('_')[0]
    coefs=np.asarray(values[1:],dtype='float32')
    embeding_index[word]=coefs
f.close()

In [11]:
len(embeding_index)

152494

In [12]:
list(embeding_index.keys())[:10]

['say', 'go', 'make', 'get', 'one', 'see', 'time', 'take', 'know', 'year']

In [0]:
import numpy as np
import pandas as pd
mcml_final = pd.read_csv("/content/mcml_final.csv")

In [0]:
mcml_final=mcml_final.dropna()

In [14]:
mcml_final.head()

Unnamed: 0                                           Question Tags
0           0  ad script function  net applic i littl game wr...   c#
1           1  use nest class case i work collect class use v...  c++
2           2  automat updat version number i would like vers...   c#
3           3  connect databas loop recordset c# what simples...   c#
4           4  get valu built  encod viewstate i need grab ba...   c#

In [0]:
mcml_final['Tags']=mcml_final['Tags'].map(lambda x:x.split(","))

In [16]:
mcml_final.iloc[6050:6060]

Unnamed: 0  ...                  Tags
6050        6050  ...                [java]
6051        6051  ...                 [c++]
6052        6052  ...                  [c#]
6053        6053  ...          [javascript]
6054        6054  ...                [java]
6055        6055  ...                  [c#]
6056        6056  ...                  [c#]
6057        6057  ...  [javascript, jquery]
6058        6058  ...                [java]
6059        6059  ...                [html]

[10 rows x 3 columns]

In [0]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split

In [0]:
multilabel_binarizer = MultiLabelBinarizer()
multilabel_binarizer.fit(mcml_final["Tags"])
labels=multilabel_binarizer.classes_

In [19]:
labels

array(['android', 'c#', 'c++', 'html', 'ios', 'java', 'javascript',
       'jquery', 'php', 'python'], dtype=object)

In [0]:
mcml_final.columns=['ind','Question','Tags']

In [21]:
mcml_final.head()

ind                                           Question   Tags
0    0  ad script function  net applic i littl game wr...   [c#]
1    1  use nest class case i work collect class use v...  [c++]
2    2  automat updat version number i would like vers...   [c#]
3    3  connect databas loop recordset c# what simples...   [c#]
4    4  get valu built  encod viewstate i need grab ba...   [c#]

In [0]:
mcml_train,mcml_test=train_test_split(mcml_final,test_size=0.2,random_state=2)

In [0]:
mcml_train1,mcml_cv=train_test_split(mcml_train,test_size=0.2,random_state=3)

In [24]:
mcml_train.shape,mcml_test.shape,mcml_train1.shape,mcml_cv.shape

((565068, 3), (141268, 3), (452054, 3), (113014, 3))

In [25]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [0]:
from nltk import word_tokenize
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from tensorflow.keras.models import Model

In [0]:
sent_lens=[]
for sent in mcml_train['Question']:
    sent_lens.append(len(word_tokenize(sent)))
    

In [28]:
max(sent_lens)    # 20667

20667

In [29]:
np.quantile(sent_lens,0.95)

623.0

In [0]:
max_len = 620

In [0]:
tok = Tokenizer(char_level=False,split=' ')

tok.fit_on_texts(mcml_train['Question'])

In [0]:
# y=multilabel_binarizer.transform(mcml_final["Tags"])

In [0]:
x_train=mcml_train['Question']
y_train=multilabel_binarizer.transform(mcml_train['Tags'])
x_test=mcml_test['Question']
y_test=multilabel_binarizer.transform(mcml_test['Tags'])

In [0]:
x_train1=mcml_train1['Question']
y_train1=multilabel_binarizer.transform(mcml_train1['Tags'])
x_cvtest=mcml_cv['Question']
y_cvtest=multilabel_binarizer.transform(mcml_cv['Tags'])


In [0]:
### Testing with validation data:

In [0]:
sequences_train1 = tok.texts_to_sequences(x_train1)

In [0]:
vocab_len1=len(tok.index_word.keys())

In [36]:
vocab_len1

1754317

In [0]:
sequences_matrix_train1 = sequence.pad_sequences(sequences_train1,maxlen=max_len)

In [38]:
sequences_matrix_train1

array([[   0,    0,    0, ...,  515,  293,  172],
       [   0,    0,    0, ...,    2,  593,    1],
       [   0,    0,    0, ...,  102,  182,  534],
       ...,
       [   0,    0,    0, ...,  621,   77,  162],
       [   0,    0,    0, ...,  490, 1704,  102],
       [   0,    0,    0, ..., 1197,   52,   14]], dtype=int32)

In [0]:
#vocab_len1=40000   # reducing the vocab_len1 for faster processing, In general the actual value is supposed to be taken
embedding_matrix=np.zeros((vocab_len1+1,300))
words_not_available=0
for word,i in tok.word_index.items():
    embed_vector=embeding_index.get(word)
    if embed_vector is not None:
        embedding_matrix[i]=embed_vector
    else:
      words_not_available+=1

In [40]:
words_not_available
# if this number is too high , you should look into alternative embeddings
# its not necessary that model performance will be low if this number is high 
# that'll be the case if these words matter in the context of the response 

1722114

In [0]:
def RNN(embedding_matrix,embed_dim,max_len,vocab_size):
    inputs = Input(name='inputs',shape=[max_len])
    
    layer = Embedding(vocab_size+1,embed_dim,input_length=max_len,
                      mask_zero=True,weights=[embedding_matrix],trainable=False)(inputs)
    layer = LSTM(64)(layer)
    layer = Dense(256,name='FC1')(layer)
    layer = Activation('relu')(layer)
    layer = Dropout(0.5)(layer)
    layer = Dense(10,name='out_layer')(layer)
    layer = Activation('sigmoid')(layer)
    model = Model(inputs=inputs,outputs=layer)
    return model

In [0]:
# def RNN():
#     inputs = Input(name='inputs',shape=[max_len])
    
#     layer = Embedding(vocab_len1+1,500,input_length=max_len,
#                       mask_zero=True)(inputs)
#     layer = LSTM(64)(layer)
#     layer = Dense(256,name='FC1')(layer)
#     layer = Activation('relu')(layer)
#     layer = Dropout(0.5)(layer)
#     layer = Dense(10,name='out_layer')(layer)
#     layer = Activation('sigmoid')(layer)
#     model = Model(inputs=inputs,outputs=layer)
#     return model

In [42]:
model1 = RNN(embedding_matrix,300,max_len,vocab_len1)
model1.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 620)]             0         
_________________________________________________________________
embedding (Embedding)        (None, 620, 300)          526295400 
_________________________________________________________________
lstm (LSTM)                  (None, 64)                93440     
_________________________________________________________________
FC1 (Dense)                  (None, 256)               16640     
_________________________________________________________________
activation (Activation)      (None, 256)               0         
_________________________________________________________________
dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
out_layer (Dense)            (None, 10)                2570  

In [0]:
model1.compile(loss='binary_crossentropy',optimizer='adam',
              metrics=['categorical_accuracy'])

In [0]:
sequences_testcv = tok.texts_to_sequences(x_cvtest)
sequences_matrix_testcv = sequence.pad_sequences(sequences_testcv,
                                               maxlen=max_len)

In [0]:
from tensorflow.keras.callbacks import ModelCheckpoint,EarlyStopping

checkpointer = ModelCheckpoint('stackoverflow_tags.hdf5', verbose=1, save_best_only=True)
earlystopper = EarlyStopping(monitor='val_loss', patience=2, verbose=1)

model1.fit(sequences_matrix_train1,y_train1,batch_size=50,
          epochs=5, callbacks=[checkpointer, earlystopper], validation_data=(sequences_matrix_testcv,y_cvtest))

Epoch 1/5
9042/9042 [==============================] - ETA: 0s - loss: 0.2713 - categorical_accuracy: 0.3892
Epoch 00001: val_loss improved from inf to 0.21217, saving model to stackoverflow_tags.hdf5
9042/9042 [==============================] - 5362s 593ms/step - loss: 0.2713 - categorical_accuracy: 0.3892 - val_loss: 0.2122 - val_categorical_accuracy: 0.5552
Epoch 2/5
9042/9042 [==============================] - ETA: 0s - loss: 0.1983 - categorical_accuracy: 0.6032
Epoch 00002: val_loss improved from 0.21217 to 0.17913, saving model to stackoverflow_tags.hdf5
9042/9042 [==============================] - 5385s 596ms/step - loss: 0.1983 - categorical_accuracy: 0.6032 - val_loss: 0.1791 - val_categorical_accuracy: 0.6424
Epoch 3/5
9042/9042 [==============================] - ETA: 0s - loss: 0.1721 - categorical_accuracy: 0.6614
Epoch 00003: val_loss improved from 0.17913 to 0.16172, saving model to stackoverflow_tags.hdf5
9042/9042 [==============================] - 5445s 602ms/step - l

In [0]:
# from google.colab import files
# files.download('/content/stackoverflow_tags.hdf5')

In [50]:
!wget https://www.dropbox.com/s/clcq0a8xf83s9tg/stackoverflow_tags.hdf5?dl=0

--2020-05-26 22:51:48--  https://www.dropbox.com/s/clcq0a8xf83s9tg/stackoverflow_tags.hdf5?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.1, 2620:100:601b:1::a27d:801
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/clcq0a8xf83s9tg/stackoverflow_tags.hdf5 [following]
--2020-05-26 22:51:48--  https://www.dropbox.com/s/raw/clcq0a8xf83s9tg/stackoverflow_tags.hdf5
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucca1e451a436fa1ecd22efc2f53.dl.dropboxusercontent.com/cd/0/inline/A4d5b9BCHsQGyvDgzw9MFImcLIKqfDxSZlQAGX1S4CMT7OFoMK3mWh3iYIxY7YhykjpPziYUBXufBOzkzgjoDh63g4o8A0o49nsM6N4hP0D91AYrXWPvgbG7S-gv9Q_IDKA/file# [following]
--2020-05-26 22:51:48--  https://ucca1e451a436fa1ecd22efc2f53.dl.dropboxusercontent.com/cd/0/inline/A4d5b9BCHsQGyvDgzw9MFImcLIKqfDxSZlQAGX1S4CMT7OFoMK3mWh3iYIxY7YhykjpPziYUBXuf

In [0]:
model1.load_weights("/content/stackoverflow_tags.hdf5")

In [0]:
### Testing with Actual Test data:

In [0]:
sequences_train = tok.texts_to_sequences(x_train)

In [0]:
vocab_len=len(tok.index_word.keys())

In [54]:
vocab_len

1754317

In [0]:
sequences_matrix_train = sequence.pad_sequences(sequences_train,maxlen=max_len)

In [56]:
sequences_matrix_train

array([[      0,       0,       0, ...,     801,     644,      78],
       [      0,       0,       0, ...,    1948,      30,     410],
       [      0,       0,       0, ...,      49,     173,    1845],
       ...,
       [      0,       0,       0, ...,     143,     445,     237],
       [      0,       0,       0, ...,    1015,     205, 1754317],
       [      0,       0,       0, ...,     337,    5710,     717]],
      dtype=int32)

In [0]:
embedding_matrix=np.zeros((vocab_len+1,300))
words_not_available=0
for word,i in tok.word_index.items():
    embed_vector=embeding_index.get(word)
    if embed_vector is not None:
        embedding_matrix[i]=embed_vector
    else:
      words_not_available+=1

In [0]:
# def RNN():
#     inputs = Input(name='inputs',shape=[max_len])
    
#     layer = Embedding(vocab_len+1,500,input_length=max_len,
#                       mask_zero=True)(inputs)
#     layer = LSTM(64)(layer)
#     layer = Dense(256,name='FC1')(layer)
#     layer = Activation('relu')(layer)
#     layer = Dropout(0.5)(layer)
#     layer = Dense(10,name='out_layer')(layer)
#     layer = Activation('sigmoid')(layer)
#     model = Model(inputs=inputs,outputs=layer)
#     return model


In [58]:
model = RNN(embedding_matrix,300,max_len,vocab_len)
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 620)]             0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 620, 300)          526295400 
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                93440     
_________________________________________________________________
FC1 (Dense)                  (None, 256)               16640     
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
out_layer (Dense)            (None, 10)                2570

In [0]:
 model.compile(loss='binary_crossentropy',optimizer='adam',
               metrics=['accuracy'])

In [0]:
sequences_test = tok.texts_to_sequences(x_test)
sequences_matrix_test = sequence.pad_sequences(sequences_test,
                                               maxlen=max_len)

In [0]:
from tensorflow.keras.callbacks import ModelCheckpoint,EarlyStopping

checkpointer = ModelCheckpoint('stackoverflow_tags_finalTest.hdf5', verbose=1, save_best_only=True)
earlystopper = EarlyStopping(monitor='val_loss', patience=2, verbose=1)

model.fit(sequences_matrix_train,y_train,batch_size=50,
          epochs=5,callbacks=[checkpointer, earlystopper], validation_data=(sequences_matrix_test,y_test))

Epoch 1/5
11302/11302 [==============================] - ETA: 0s - loss: 0.2899 - accuracy: 0.3415
Epoch 00001: val_loss improved from inf to 0.22768, saving model to stackoverflow_tags_finalTest.hdf5
11302/11302 [==============================] - 6820s 603ms/step - loss: 0.2899 - accuracy: 0.3415 - val_loss: 0.2277 - val_accuracy: 0.5131
Epoch 2/5
11302/11302 [==============================] - ETA: 0s - loss: 0.2111 - accuracy: 0.5667
Epoch 00002: val_loss improved from 0.22768 to 0.18392, saving model to stackoverflow_tags_finalTest.hdf5
11302/11302 [==============================] - 7108s 629ms/step - loss: 0.2111 - accuracy: 0.5667 - val_loss: 0.1839 - val_accuracy: 0.6331
Epoch 3/5
11302/11302 [==============================] - ETA: 0s - loss: 0.1758 - accuracy: 0.6507
Epoch 00003: val_loss improved from 0.18392 to 0.16501, saving model to stackoverflow_tags_finalTest.hdf5
11302/11302 [==============================] - 7147s 632ms/step - loss: 0.1758 - accuracy: 0.6507 - val_loss:

In [61]:
!wget https://www.dropbox.com/s/flac1dbcyxp02im/stackoverflow_tags_finalTest.hdf5?dl=0

--2020-05-26 22:55:57--  https://www.dropbox.com/s/flac1dbcyxp02im/stackoverflow_tags_finalTest.hdf5?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.1, 2620:100:601b:1::a27d:801
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/flac1dbcyxp02im/stackoverflow_tags_finalTest.hdf5 [following]
--2020-05-26 22:55:57--  https://www.dropbox.com/s/raw/flac1dbcyxp02im/stackoverflow_tags_finalTest.hdf5
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc180d2821e5ed6736441628f220.dl.dropboxusercontent.com/cd/0/inline/A4dh4rQseuxNSmU_c8i3Vk59dLKxev6mJLw-q7csi3J8xO27sNOx1vXuJZT_m927fcP2bU4sdRFwYXn0xlNL62VHUpuay7Vwf5qkw1asvq4bR3sB_C8TL_z6o5zvkOx_fkI/file# [following]
--2020-05-26 22:55:57--  https://uc180d2821e5ed6736441628f220.dl.dropboxusercontent.com/cd/0/inline/A4dh4rQseuxNSmU_c8i3Vk59dLKxev6mJLw-q7csi3J8xO

In [0]:
model.load_weights("/content/stackoverflow_tags_finalTest.hdf5")

In [0]:
from google.colab import files
files.download('/content/stackoverflow_tags_finalTest.hdf5')

In [66]:
# Use this if loading weights from hdf5 file
results = model.evaluate(sequences_matrix_test, y_test, batch_size=50)

2826/2826 [==============================] - 540s 191ms/step - loss: 0.1485 - accuracy: 0.6971


In [0]:
predictions=model.predict(sequences_matrix_test)

In [64]:
predictions

array([[2.2542477e-04, 4.9015880e-04, 4.1788816e-04, ..., 2.7949572e-02,
        9.8452741e-01, 3.5142899e-04],
       [5.1836432e-05, 9.9419332e-01, 6.8077445e-04, ..., 7.9703331e-04,
        2.1234155e-04, 7.0162218e-06],
       [2.3355365e-02, 1.0772645e-03, 7.3084235e-04, ..., 3.1620264e-04,
        1.3792217e-03, 4.3719113e-03],
       ...,
       [5.4904819e-04, 5.5809319e-03, 7.1194172e-03, ..., 3.5151541e-03,
        4.3464899e-03, 9.6180177e-01],
       [9.6402764e-03, 8.9490205e-02, 2.0678744e-01, ..., 4.1137069e-02,
        5.5736452e-02, 2.8294295e-02],
       [1.3800859e-03, 1.4184564e-02, 3.1068921e-04, ..., 7.6932716e-01,
        2.2395164e-02, 2.4935901e-03]], dtype=float32)

In [0]:
from sklearn import metrics

In [69]:
metrics.roc_auc_score(y_test,predictions)

0.9542710061035207

In [71]:
labels = np.argmax(predictions, axis=-1)    
print(labels)


[8 1 5 ... 9 6 7]


In [70]:
labels = (predictions > 0.5).astype(np.int)
print(labels)

[[0 0 0 ... 0 1 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]]
