In [0]:
%tensorflow_version 2.x

In [2]:
!wget https://www.dropbox.com/s/1ahv8t16ru15fjb/genres_data.csv?dl=0

--2020-05-25 10:42:04--  https://www.dropbox.com/s/1ahv8t16ru15fjb/genres_data.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/1ahv8t16ru15fjb/genres_data.csv [following]
--2020-05-25 10:42:04--  https://www.dropbox.com/s/raw/1ahv8t16ru15fjb/genres_data.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc2501c8aaa15a8a0dd24823ee80.dl.dropboxusercontent.com/cd/0/inline/A4asrsKKFzDrUCPjsKBeqy0wrc8EXHCOyJZvQ2k79wK9yb8cqx8H0e0w_y14DaVgShnoRwcINodPXJaLlrhJw5sUzSpwvOm2Chts8JRlkO0Izm0j-0mpbGnIczwFpYBWL24/file# [following]
--2020-05-25 10:42:04--  https://uc2501c8aaa15a8a0dd24823ee80.dl.dropboxusercontent.com/cd/0/inline/A4asrsKKFzDrUCPjsKBeqy0wrc8EXHCOyJZvQ2k79wK9yb8cqx8H0e0w_y14DaVgShnoRwcINodPXJaLlrhJw5sUzSpwvOm2Chts

In [3]:
!wget https://www.dropbox.com/s/vwgv50qp6gkx1n9/audio.tar?dl=0

--2020-05-25 10:42:38--  https://www.dropbox.com/s/vwgv50qp6gkx1n9/audio.tar?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/vwgv50qp6gkx1n9/audio.tar [following]
--2020-05-25 10:42:38--  https://www.dropbox.com/s/raw/vwgv50qp6gkx1n9/audio.tar
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucb031853e418e68ad55ac178028.dl.dropboxusercontent.com/cd/0/inline/A4byYJ5AmQxBvC-p1oWX3sgn43ydnf7g32r-9IMda79Zt8HGPxIGqVgnqN6O_n-7nMnOxZwLLww7eMAViHBxEODpEnkgrkhOfHdrOqbcDy5d2QXmKce7cYVGjrhlRovQIwo/file# [following]
--2020-05-25 10:42:38--  https://ucb031853e418e68ad55ac178028.dl.dropboxusercontent.com/cd/0/inline/A4byYJ5AmQxBvC-p1oWX3sgn43ydnf7g32r-9IMda79Zt8HGPxIGqVgnqN6O_n-7nMnOxZwLLww7eMAViHBxEODpEnkgrkhOfHdrOqbcDy5d2QXmKce7cY

In [0]:
!tar -xf /content/audio.tar

In [0]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
from PIL import Image
import pathlib
import csv

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler


import warnings
warnings.filterwarnings('ignore')

In [0]:
from tensorflow.keras.layers import Lambda,Conv1D, MaxPooling1D,Activation, Dense,BatchNormalization
from tensorflow.keras.models import Sequential

In [0]:
mypath=os.getcwd()

In [8]:
os.listdir('/content/audio/blues')

['blues.00076.wav',
 'blues.00037.wav',
 'blues.00013.wav',
 'blues.00045.wav',
 'blues.00004.wav',
 'blues.00046.wav',
 'blues.00095.wav',
 'blues.00069.wav',
 'blues.00026.wav',
 'blues.00065.wav',
 'blues.00080.wav',
 'blues.00073.wav',
 'blues.00003.wav',
 'blues.00032.wav',
 'blues.00089.wav',
 'blues.00009.wav',
 'blues.00010.wav',
 'blues.00051.wav',
 'blues.00042.wav',
 'blues.00030.wav',
 'blues.00086.wav',
 'blues.00088.wav',
 'blues.00055.wav',
 'blues.00050.wav',
 'blues.00057.wav',
 'blues.00025.wav',
 'blues.00060.wav',
 'blues.00049.wav',
 'blues.00015.wav',
 'blues.00054.wav',
 'blues.00014.wav',
 'blues.00064.wav',
 'blues.00043.wav',
 'blues.00005.wav',
 'blues.00031.wav',
 'blues.00033.wav',
 'blues.00034.wav',
 'blues.00028.wav',
 'blues.00038.wav',
 'blues.00070.wav',
 'blues.00062.wav',
 'blues.00029.wav',
 'blues.00012.wav',
 'blues.00053.wav',
 'blues.00018.wav',
 'blues.00001.wav',
 'blues.00011.wav',
 'blues.00039.wav',
 'blues.00077.wav',
 'blues.00082.wav',


In [0]:
# cmap = plt.get_cmap('inferno')

# plt.figure(figsize=(10,10))
# genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split()
# for g in genres:
#     pathlib.Path(f'img_data/{g}').mkdir(parents=True, exist_ok=True)     
#     for filename in os.listdir(f'./audio/{g}'):
#         songname = f'./audio/{g}/{filename}'
#         print(songname)

./audio/blues/blues.00000.wav
./audio/blues/blues.00001.wav
./audio/blues/blues.00002.wav
./audio/blues/blues.00003.wav
./audio/blues/blues.00004.wav
./audio/blues/blues.00005.wav
./audio/blues/blues.00006.wav
./audio/blues/blues.00007.wav
./audio/blues/blues.00008.wav
./audio/blues/blues.00009.wav
./audio/blues/blues.00010.wav
./audio/blues/blues.00011.wav
./audio/blues/blues.00012.wav
./audio/blues/blues.00013.wav
./audio/blues/blues.00014.wav
./audio/blues/blues.00015.wav
./audio/blues/blues.00016.wav
./audio/blues/blues.00017.wav
./audio/blues/blues.00018.wav
./audio/blues/blues.00019.wav
./audio/blues/blues.00020.wav
./audio/blues/blues.00021.wav
./audio/blues/blues.00022.wav
./audio/blues/blues.00023.wav
./audio/blues/blues.00024.wav
./audio/blues/blues.00025.wav
./audio/blues/blues.00026.wav
./audio/blues/blues.00027.wav
./audio/blues/blues.00028.wav
./audio/blues/blues.00029.wav
./audio/blues/blues.00030.wav
./audio/blues/blues.00031.wav
./audio/blues/blues.00032.wav
./audio/bl

./audio/disco/disco.00000.wav
./audio/disco/disco.00001.wav
./audio/disco/disco.00002.wav
./audio/disco/disco.00003.wav
./audio/disco/disco.00004.wav
./audio/disco/disco.00005.wav
./audio/disco/disco.00006.wav
./audio/disco/disco.00007.wav
./audio/disco/disco.00008.wav
./audio/disco/disco.00009.wav
./audio/disco/disco.00010.wav
./audio/disco/disco.00011.wav
./audio/disco/disco.00012.wav
./audio/disco/disco.00013.wav
./audio/disco/disco.00014.wav
./audio/disco/disco.00015.wav
./audio/disco/disco.00016.wav
./audio/disco/disco.00017.wav
./audio/disco/disco.00018.wav
./audio/disco/disco.00019.wav
./audio/disco/disco.00020.wav
./audio/disco/disco.00021.wav
./audio/disco/disco.00022.wav
./audio/disco/disco.00023.wav
./audio/disco/disco.00024.wav
./audio/disco/disco.00025.wav
./audio/disco/disco.00026.wav
./audio/disco/disco.00027.wav
./audio/disco/disco.00028.wav
./audio/disco/disco.00029.wav
./audio/disco/disco.00030.wav
./audio/disco/disco.00031.wav
./audio/disco/disco.00032.wav
./audio/di

<Figure size 720x720 with 0 Axes>

Extracting music and features
Dataset
The dataset consists of 10 genres i.e

Blues
Classical
Country
Disco
Hiphop
Jazz
Metal
Pop
Reggae
Rock
Each genre contains 100 songs. Total dataset: 1000 songs


### Extracting the Spectrogram for each audio

In [9]:
cmap = plt.get_cmap('inferno')

plt.figure(figsize=(10,10))
genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split()
for g in genres:
    pathlib.Path(f'img_data/{g}').mkdir(parents=True, exist_ok=True)     
    for filename in os.listdir(f'./audio/{g}'):
        songname = f'./audio/{g}/{filename}'
        y, sr = librosa.load(songname, mono=True, duration=5)
        plt.specgram(y, NFFT=2048, Fs=2, Fc=0, noverlap=128, cmap=cmap, sides='default', mode='default', scale='dB');
        plt.axis('off');
        plt.savefig(f'img_data/{g}/{filename[:-3].replace(".", "")}.png')
        plt.clf()

<Figure size 720x720 with 0 Axes>

#### Extracting features from Spectrogram

    Mel-frequency cepstral coefficients (MFCC)(20 in number)
    Spectral Centroid,
    Zero Crossing Rate
    Chroma Frequencies
    Spectral Roll-off.

In [0]:
header = 'filename chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
for i in range(1, 21):
    header += f' mfcc{i}'
header += ' label'
header = header.split()

#### Writing Data to a CSV file:

In [0]:
file = open('genres_data.csv', 'w', newline='')
with file:
    writer = csv.writer(file)
    writer.writerow(header)
genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split()
for g in genres:
    for filename in os.listdir(f'./audio/{g}'):
        songname = f'./audio/{g}/{filename}'
        y, sr = librosa.load(songname, mono=True, duration=30)
        chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
        rmse = librosa.feature.rms(y=y)
        spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
        spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
        rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
        zcr = librosa.feature.zero_crossing_rate(y)
        mfcc = librosa.feature.mfcc(y=y, sr=sr)
        to_append = f'{filename} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'    
        for e in mfcc:
            to_append += f' {np.mean(e)}'
        to_append += f' {g}'
        file = open('genres_data.csv', 'a', newline='')
        with file:
            writer = csv.writer(file)
            writer.writerow(to_append.split())

In [12]:
data = pd.read_csv('genres_data.csv')
data.head()

filename  chroma_stft      rmse  ...    mfcc19     mfcc20  label
0  blues.00076.wav     0.365575  0.219080  ... -4.947726   4.426066  blues
1  blues.00037.wav     0.248627  0.069145  ... -4.470060  -3.688800  blues
2  blues.00013.wav     0.264616  0.113221  ... -1.769590  -7.762958  blues
3  blues.00045.wav     0.429511  0.148366  ... -8.565096   1.857711  blues
4  blues.00004.wav     0.308590  0.091563  ... -4.409333 -11.703781  blues

[5 rows x 28 columns]

In [13]:
data.shape

(1000, 28)

In [0]:
# Dropping unneccesary columns
data = data.drop(['filename'],axis=1)

#### Encoding the Labels:

In [0]:
genre_list = data.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)

In [16]:
data.head()

chroma_stft      rmse  spectral_centroid  ...    mfcc19     mfcc20  label
0     0.365575  0.219080        2645.681661  ... -4.947726   4.426066  blues
1     0.248627  0.069145        1188.168337  ... -4.470060  -3.688800  blues
2     0.264616  0.113221        1324.304356  ... -1.769590  -7.762958  blues
3     0.429511  0.148366        1739.019621  ... -8.565096   1.857711  blues
4     0.308590  0.091563        1835.494603  ... -4.409333 -11.703781  blues

[5 rows x 27 columns]

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

#### Scaling the Feature columns:

In [0]:
scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))

In [19]:
X

array([[-0.16033059,  1.34269768,  0.62024232, ...,  0.82286806,
        -0.69769814,  1.43937848],
       [-1.59237717, -0.94107001, -1.41651935, ..., -2.55375936,
        -0.57044605, -0.67626901],
       [-1.39659575, -0.26971539, -1.22627984, ..., -0.57231381,
         0.14897039, -1.7384531 ],
       ...,
       [ 0.29217563, -0.78784386,  0.65314315, ..., -0.21397458,
        -0.00291025, -0.84113756],
       [-0.43014795, -0.38287668, -0.36596831, ...,  0.28782284,
        -2.23170992,  0.14422015],
       [ 0.70093883, -0.28484831,  0.16678446, ...,  0.70568278,
        -0.63504463,  0.20240124]])

#### Dividing the data into train and test data:

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 26), (200, 26), (800,), (200,))

#### Building our Network:

In [0]:
model = Sequential()

model.add(Dense(256, activation='relu', input_shape=(X_train.shape[1],)))

model.add(Dense(128, activation='relu'))

model.add(Dense(64, activation='relu'))

model.add(Dense(10, activation='softmax'))

In [0]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
history = model.fit(X_train,
                    y_train,
                    epochs=20,
                    batch_size=128)

Epoch 1/20
7/7 [==============================] - 0s 3ms/step - loss: 2.1965 - accuracy: 0.2412
Epoch 2/20
7/7 [==============================] - 0s 4ms/step - loss: 1.9365 - accuracy: 0.3413
Epoch 3/20
7/7 [==============================] - 0s 2ms/step - loss: 1.7383 - accuracy: 0.3700
Epoch 4/20
7/7 [==============================] - 0s 2ms/step - loss: 1.5696 - accuracy: 0.4500
Epoch 5/20
7/7 [==============================] - 0s 2ms/step - loss: 1.4262 - accuracy: 0.5025
Epoch 6/20
7/7 [==============================] - 0s 3ms/step - loss: 1.2982 - accuracy: 0.5462
Epoch 7/20
7/7 [==============================] - 0s 2ms/step - loss: 1.1956 - accuracy: 0.6087
Epoch 8/20
7/7 [==============================] - 0s 3ms/step - loss: 1.1086 - accuracy: 0.6400
Epoch 9/20
7/7 [==============================] - 0s 2ms/step - loss: 1.0372 - accuracy: 0.6675
Epoch 10/20
7/7 [==============================] - 0s 2ms/step - loss: 0.9697 - accuracy: 0.6862
Epoch 11/20
7/7 [======================

In [25]:
test_loss, test_acc = model.evaluate(X_test,y_test)

7/7 [==============================] - 0s 2ms/step - loss: 0.9142 - accuracy: 0.7000


In [26]:
print('test_acc: ',test_acc)

test_acc:  0.699999988079071


In [0]:
predictions = model.predict(X_test)

In [28]:
predictions[0].shape

(10,)

In [29]:
y_test

array([8, 3, 8, 8, 7, 1, 8, 9, 6, 4, 8, 3, 2, 5, 9, 3, 8, 7, 2, 1, 6, 4,
       5, 8, 8, 7, 6, 5, 4, 7, 9, 8, 8, 8, 1, 9, 4, 9, 5, 8, 5, 8, 0, 0,
       5, 0, 0, 5, 7, 8, 0, 1, 8, 1, 1, 7, 2, 9, 1, 7, 0, 7, 4, 1, 8, 4,
       2, 3, 3, 6, 7, 8, 1, 4, 1, 5, 6, 7, 0, 1, 9, 1, 2, 6, 7, 4, 5, 7,
       3, 3, 1, 2, 1, 5, 2, 4, 5, 9, 9, 5, 7, 9, 8, 0, 8, 6, 0, 5, 6, 5,
       8, 3, 6, 2, 3, 9, 1, 8, 1, 4, 1, 7, 6, 9, 0, 7, 7, 2, 5, 8, 6, 0,
       4, 5, 1, 8, 9, 2, 5, 6, 3, 6, 2, 1, 8, 4, 4, 3, 2, 2, 0, 0, 0, 7,
       8, 6, 2, 9, 9, 0, 2, 8, 9, 6, 0, 7, 4, 0, 4, 8, 7, 4, 5, 8, 4, 4,
       7, 7, 3, 0, 9, 9, 4, 2, 8, 4, 2, 8, 3, 4, 5, 0, 2, 2, 4, 3, 6, 1,
       3, 0])

In [0]:
labels_test_predicted1=np.argmax(predictions,1)

In [31]:
labels_test_predicted1

array([8, 3, 8, 2, 7, 1, 5, 3, 6, 3, 9, 3, 3, 9, 9, 3, 2, 7, 2, 1, 6, 4,
       9, 8, 3, 7, 6, 5, 4, 7, 3, 8, 8, 7, 1, 9, 3, 9, 2, 8, 5, 8, 0, 6,
       8, 5, 2, 8, 7, 8, 0, 1, 8, 1, 1, 7, 2, 3, 1, 8, 6, 7, 4, 1, 8, 3,
       2, 3, 3, 6, 7, 8, 1, 4, 1, 5, 6, 7, 0, 1, 0, 1, 2, 6, 7, 4, 1, 7,
       3, 3, 1, 2, 1, 2, 2, 4, 5, 3, 9, 5, 7, 9, 8, 0, 8, 6, 0, 5, 6, 1,
       0, 3, 6, 5, 3, 9, 1, 6, 1, 2, 1, 7, 6, 9, 0, 7, 7, 2, 5, 8, 6, 0,
       4, 2, 1, 3, 3, 5, 9, 6, 3, 6, 2, 1, 2, 4, 4, 8, 2, 2, 0, 5, 2, 7,
       8, 6, 2, 3, 3, 0, 2, 8, 3, 6, 2, 3, 6, 0, 7, 8, 3, 6, 5, 8, 8, 8,
       7, 7, 3, 9, 9, 3, 4, 5, 4, 4, 2, 4, 3, 4, 5, 0, 8, 2, 4, 3, 6, 8,
       0, 0])

In [32]:
pd.crosstab(y_test,labels_test_predicted1)

col_0   0   1   2   3   4  5   6   7   8  9
row_0                                      
0      12   0   3   0   0  2   2   0   0  1
1       0  19   0   0   0  0   0   0   1  0
2       0   0  14   1   0  3   0   0   1  0
3       1   0   0  13   0  0   0   0   1  0
4       0   0   1   3  13  0   2   1   2  0
5       0   2   3   0   0  9   0   0   2  3
6       0   0   0   0   0  0  16   0   0  0
7       0   0   0   2   0  0   0  18   1  0
8       1   0   3   2   2  1   1   1  18  1
9       1   0   0   9   0  0   0   0   0  8

In [33]:
(y_test==labels_test_predicted1).sum()

140

In [0]:
a=y_test==labels_test_predicted1

In [0]:
al_eq=[i for i,j in enumerate(a) if not j]

In [36]:
al_eq

[3,
 6,
 7,
 9,
 10,
 12,
 13,
 16,
 22,
 24,
 30,
 33,
 36,
 38,
 43,
 44,
 45,
 46,
 47,
 57,
 59,
 60,
 65,
 80,
 86,
 93,
 97,
 109,
 110,
 113,
 117,
 119,
 133,
 135,
 136,
 137,
 138,
 144,
 147,
 151,
 152,
 157,
 158,
 162,
 164,
 165,
 166,
 168,
 170,
 171,
 174,
 175,
 179,
 181,
 183,
 184,
 187,
 192,
 197,
 198]

In [37]:
np.sum(predictions[0])

1.0

In [38]:
X_test[25]

array([-0.40422164,  0.03981156,  0.4426634 ,  0.83894724,  0.58732523,
       -0.08355839,  0.32831751, -0.44624632,  0.5735182 , -1.19631771,
        0.2750735 , -0.73132433,  0.00807304, -1.34612615,  0.83402642,
       -0.77576183,  0.033199  , -1.42375965,  0.74363629, -1.23735152,
        0.6357123 ,  0.09057738,  0.95280735,  0.01797562,  0.43649395,
       -0.18740716])

In [0]:
ind_label=pd.DataFrame(list(zip(genres,list(range(0, 10)))), columns=['label','ind'])

In [40]:
ind_label[ind_label['ind']==0].label

0    blues
Name: label, dtype: object

In [43]:
ind=25
sample_music = X_test[ind] 
r=y_test[ind]
p=labels_test_predicted1[ind]
l1=ind_label[ind_label['ind']==r].label
l2=ind_label[ind_label['ind']==p].label
print('real label:',l1)
print('predicted label:',l2)

real label: 7    pop
Name: label, dtype: object
predicted label: 7    pop
Name: label, dtype: object
